# Generated by Django 3.1.7 on 2021-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210308_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('uppdated_at', models.DateField(auto_now=True, verbose_name='Uppdate Date')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blog',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
