# Generated by Django 3.1.7 on 2021-03-08 09:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210308_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='Text'),
        ),
    ]
